<?php
Route::get('seller/gator/{user_id?}','GatorController@index')->name('gator');
Route::get('/seller/gatorbuyer/modal/{user_id?}','GatorController@gatorBuyer');
Route::get('/seller/gator/saleorder/{user_id}','GatorController@displaySaleOrder');
/*
Route::get('seller/gatorproduct/{id}','GatorController@productdetail');
Route::get('seller/addgatorproductsession/{id}','GatorController@addinsession');
Route::get('seller/removefromsession/{id}','GatorController@destroyfromsession');
*/
Route::post('seller/checkoutgator','GatorController@save')->name('checkoutgator');
Route::post('seller/gatorconfirm','GatorController@show');
Route::post('seller/gatornewbuyer','GatorController@savebuyer');
Route::post('/gator/salesorder','StatementController@salesorderdocument');
Route::get('/DO/displaysalesorderdocument/{id}/{nid?}/{heading?}','GatorController@displaysalesorderdocument')->name('displaysalesorderdocument');
Route::get('/seller/deletegatorbuyer/{id}','GatorController@deletegatorbuyer');
Route::get('/seller/unlinkgatorbuyer/{id}{user_id?}','GatorController@unlinkgatorbuyer');
Route::get('/seller/emerchantdetail/{id}','GatorController@emerchantdetail');
?>
