@include("common.head")
<style>
.jaguar{
	background-size: 490px 710px;
	background-repeat: no-repeat;
	background-position: center center;
	background-image:url('/images/cprofile/jaguar-A4.png');
}
</style>
<body>
	@include("cprofile.header")
	<div class="container" style="margin:0;padding:0;width:980px !important; height: 660px !important;">
		<div class="jaguar" style="padding:0;width:490px !important; height: 660px !important; float: left;">
			<p style="color: white; font-size: 30px; margin-left: 35px; margin-top: 200px"><b>Jaguar 1.0</b></p>
			<p style="color: white; font-size: 30px; margin-left: 35px; margin-top: -10px;"><b>New Creation</b></p>
			<p style="color: white; font-size: 17px; margin-left: 35px; margin-top: -10px;">Credit Term System</p>
			
		</div>
		<div style="padding:0;width:470px !important; height: 660px !important; float: left; padding-right: 30px;">
			<p style="font-size: 36px; margin-left: -75px; margin-top: 80px"><b>Jaguar</b> 1.0 (New Creation)</p>
			<p style="font-size: 28px; margin-left: -75px; margin-top: -10px;">Credit Term System</p>
			<p style="font-size: 15px; margin-left: 50px; margin-top: 20px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;OpenSupermall has an extensive online system based on the traditional definition credit term. Given a credit limit and credit term which is definable by a merchant or seller towards any or their dealers or any party which they want to do business in a traditional credit term environment yet with the advantages of being online.</p>
			<p style="font-size: 15px; margin-left: 50px; margin-top: 20px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Credit limit and credit term are constantly being monitored by the system for both the dealer and the supplier. For the dealers, the system will be tracking as to how much is owed to whom, and for the suppliers/merchants, their debtors would be tracked. In the same vein, payment from the debtors are
			<p style="font-size: 15px; margin-left: 50px; margin-top: 20px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;All related paperwork, purchase orders, invoices, receipts are automatically generated by the system during the procurement process. Historical documents are cleanly and neatly archived in months and years for easy access. All documents are available as a PDF download if required.</p>
		</div>
		
	</div>
</body>
